image: node:14

stages:
  - test

tests:
  stage: test
  script:
    - cd ui && npm ci
    - npm test
  rules:
    - if: $CI_COMMIT_BRANCH == 'master' || $CI_PIPELINE_SOURCE == 'merge_request_event' 
